<?php

namespace AppBundle\Repository;

/**
 * UsuarioCategiriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioCategiriaRepository extends \Doctrine\ORM\EntityRepository
{
}
